"""Find the logical operators (and code distance) of a CSS code.

The check-matrix file contains a ``Z checks`` section followed by an
``X checks`` section, each a 0/1 matrix with one row per stabilizer and one
column per physical qubit.

For a CSS code with X-check matrix ``Hx`` and Z-check matrix ``Hz``:
  * Z-type logical operators live in  ker(Hx) \\ rowspace(Hz)
  * X-type logical operators live in  ker(Hz) \\ rowspace(Hx)
  * number of logical qubits  k = n - rank(Hx) - rank(Hz)

All linear algebra is done over GF(2).

Usage:  python distance_check.py [check_matrix_file]
"""

from __future__ import annotations

import math
import multiprocessing as mp
import os
import sys
import time
from itertools import combinations

import numpy as np


# --------------------------------------------------------------------------- #
# Parsing
# --------------------------------------------------------------------------- #
def load_check_matrices(path: str) -> tuple[np.ndarray, np.ndarray]:
    """Parse a check-matrix file into (Hz, Hx) binary matrices."""
    sections: dict[str, list[list[int]]] = {}
    current: str | None = None

    with open(path) as fh:
        for raw in fh:
            line = raw.strip()
            if not line:
                continue
            lowered = line.lower()
            if lowered.startswith("z check"):
                current = "Z"
                sections[current] = []
            elif lowered.startswith("x check"):
                current = "X"
                sections[current] = []
            elif set(line) <= {"0", "1"} and current is not None:
                sections[current].append([int(c) for c in line])

    Hz = np.array(sections["Z"], dtype=np.int8)
    Hx = np.array(sections["X"], dtype=np.int8)
    return Hz, Hx


# --------------------------------------------------------------------------- #
# GF(2) linear algebra
# --------------------------------------------------------------------------- #
def rref_gf2(mat: np.ndarray) -> tuple[np.ndarray, list[int]]:
    """Reduced row echelon form over GF(2). Returns (rref, pivot columns)."""
    m = mat.copy().astype(np.int8) % 2
    rows, cols = m.shape
    pivots: list[int] = []
    r = 0
    for c in range(cols):
        if r == rows:
            break
        below = np.flatnonzero(m[r:, c])
        if len(below) == 0:
            continue
        pivot = r + below[0]
        m[[r, pivot]] = m[[pivot, r]]
        others = np.flatnonzero(m[:, c])
        others = others[others != r]
        m[others] ^= m[r]
        pivots.append(c)
        r += 1
    return m[:r], pivots


def rank_gf2(mat: np.ndarray) -> int:
    return len(rref_gf2(mat)[1]) if mat.size else 0


def null_space_gf2(mat: np.ndarray) -> np.ndarray:
    """Basis for the right null space {v : mat @ v = 0} over GF(2): one vector
    per free column, in ascending column order."""
    if mat.size == 0:
        return np.eye(0, dtype=np.int8)
    rref, pivots = rref_gf2(mat)
    cols = mat.shape[1]
    free = [c for c in range(cols) if c not in set(pivots)]
    basis = np.zeros((len(free), cols), dtype=np.int8)
    for i, f in enumerate(free):
        basis[i, f] = 1
        basis[i, pivots] = rref[:, f]
    return basis


def in_rowspace_gf2(vec: np.ndarray, basis_rref: np.ndarray, pivots: list[int]) -> bool:
    """Is ``vec`` in the row space described by (rref basis, pivot columns)?"""
    v = vec.copy().astype(np.int8) % 2
    for row, piv in zip(basis_rref, pivots):
        if v[piv]:
            v ^= row
    return not v.any()


class _Span:
    """A growing GF(2) subspace.  ``add(v)`` inserts ``v`` and tells whether it
    was new (independent of everything added before)."""

    def __init__(self) -> None:
        self.rows: list[tuple[int, np.ndarray]] = []  # (leading column, row)

    def add(self, vec: np.ndarray) -> bool:
        v = vec.copy().astype(np.int8) % 2
        for lead, row in self.rows:
            if v[lead]:
                v ^= row
        if not v.any():
            return False
        self.rows.append((int(np.argmax(v)), v))
        return True


# --------------------------------------------------------------------------- #
# Logical operators
# --------------------------------------------------------------------------- #
def logical_operators(kernel_basis: np.ndarray, stab: np.ndarray) -> np.ndarray:
    """Independent logical operators (mod stabilizers): the kernel vectors, in
    order, that are not generated by ``stab`` and the ones already chosen."""
    span = _Span()
    for row in stab:
        span.add(row)
    logicals = [v.copy() for v in kernel_basis if span.add(v)]
    if not logicals:
        return np.zeros((0, kernel_basis.shape[1]), np.int8)
    return np.array(logicals, dtype=np.int8)


def invert_gf2(mat: np.ndarray) -> np.ndarray:
    """Inverse of a square matrix over GF(2) (via Gauss-Jordan)."""
    n = mat.shape[0]
    if mat.shape[1] != n:
        raise ValueError("invert_gf2 expects a square matrix")
    aug = np.concatenate([mat.astype(np.int8) % 2, np.eye(n, dtype=np.int8)], axis=1)
    rref, pivots = rref_gf2(aug)
    if pivots[:n] != list(range(n)):
        raise ValueError("matrix is singular over GF(2)")
    return rref[:, n:]


def pair_logical_operators(
    logical_X: np.ndarray, logical_Z: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    """Symplectically pair X- and Z-type logicals into logical qubits.

    Returns ``(X_paired, logical_Z)`` with ``X_paired[i] . logical_Z[j] ==
    delta_ij`` over GF(2), so ``(X_paired[i], logical_Z[i])`` is the
    anticommuting pair that defines logical qubit ``i``.

    The Z basis is kept and only the X basis is re-mixed: with the overlap
    matrix ``M[i, j] = X[i] . Z[j]`` (invertible for a valid code),
    ``X_paired = M^{-1} X`` gives ``X_paired . Z^T = I``.
    """
    if logical_X.shape[0] != logical_Z.shape[0]:
        raise ValueError("need equally many X- and Z-type logicals")
    if logical_X.shape[0] == 0:
        return logical_X.copy(), logical_Z.copy()
    X64 = logical_X.astype(np.int64)
    M = X64 @ logical_Z.astype(np.int64).T % 2
    X_paired = invert_gf2(M).astype(np.int64) @ X64 % 2
    return X_paired.astype(np.int8), logical_Z.astype(np.int8)


def all_kernel_weights_even(H: np.ndarray) -> bool:
    """True iff every ``v`` with ``H @ v == 0`` has even weight, i.e. the
    all-ones vector lies in ``rowspace(H)``."""
    if H.size == 0:
        return H.shape[1] == 0
    return in_rowspace_gf2(np.ones(H.shape[1], dtype=np.int8), *rref_gf2(H))


# --------------------------------------------------------------------------- #
# 0/1 vectors as Python ints (bit j == entry j)
# --------------------------------------------------------------------------- #
def _row_as_int(row: np.ndarray) -> int:
    """Encode a 0/1 vector as an int (bit ``j`` == ``row[j]``)."""
    packed = np.packbits(np.asarray(row, dtype=np.uint8), bitorder="little")
    return int.from_bytes(packed.tobytes(), "little")


def _columns_as_int(mat: np.ndarray) -> list[int]:
    """Encode each column of ``mat`` as an int (bit ``i`` == ``mat[i, j]``)."""
    return [_row_as_int(col) for col in mat.T]


def _vints_to_matrix(vints, n: int) -> np.ndarray:
    """Sorted, de-duplicated bitmasks as the rows of a 0/1 matrix."""
    vints = sorted(set(int(v) for v in vints))
    rows = [[(v >> j) & 1 for j in range(n)] for v in vints]
    return np.array(rows, dtype=np.int8).reshape(len(vints), n)


def fmt(vec: np.ndarray) -> str:
    return "".join(str(int(b)) for b in vec)


# --------------------------------------------------------------------------- #
# Stabilizer test and brute-force reference search
#
# The worker globals below hold the columns of H and the stabilizer RREF as
# ints.  The brute-force search walks the C(n, w) supports of a weight ``w``
# one at a time, split across workers by their ``PREFIX_LEN`` smallest
# indices.  It is only usable for small ``n`` / ``w`` and is kept to
# cross-check the meet-in-the-middle search (and for ``search_d8.py``).
# --------------------------------------------------------------------------- #
PREFIX_LEN = 2  # columns fixed per brute-force task

_COLS: list[int] = []  # columns of H
_STAB_PIV: list[int] = []  # pivot columns of the stabilizer RREF
_RREF_INTS: list[int] = []  # rows of the stabilizer RREF
_N = 0
_FOUND = None  # multiprocessing.Value: "this weight is solved, stop"


def _init_worker(cols, stab_piv, rref_ints, n, found):
    global _COLS, _STAB_PIV, _RREF_INTS, _N, _FOUND
    _COLS, _STAB_PIV, _RREF_INTS, _N, _FOUND = cols, stab_piv, rref_ints, n, found


def _is_stabilizer(vint: int) -> bool:
    for piv, row in zip(_STAB_PIV, _RREF_INTS):
        if (vint >> piv) & 1:
            vint ^= row
    return vint == 0


def _prefix_hits(prefix: tuple[int, ...], w: int):
    """Yield (as bitmasks) the weight-``w`` supports with smallest indices
    ``prefix`` that lie in ``ker(H)`` and are not stabilizers."""
    for tail in combinations(range(prefix[-1] + 1, _N), w - len(prefix)):
        syn = vint = 0
        for j in prefix + tail:
            syn ^= _COLS[j]
            vint |= 1 << j
        if syn == 0 and not _is_stabilizer(vint):
            yield vint


def _search_prefix(task: tuple[tuple[int, ...], int]) -> bool:
    """Is there any hit for this ``(prefix, w)``?  (False once another task
    has already solved the weight.)"""
    if _FOUND is not None and _FOUND.value:
        return False
    return next(_prefix_hits(*task), None) is not None


def _collect_prefix(task: tuple[tuple[int, ...], int]) -> list[int]:
    """Every hit for this ``(prefix, w)``."""
    return list(_prefix_hits(*task))


def _brute_pool(H: np.ndarray, stab: np.ndarray, nprocs: int | None):
    stab_rref, stab_piv = rref_gf2(stab)
    found = mp.Value("b", 0)
    args = (
        _columns_as_int(H),
        stab_piv,
        [_row_as_int(r) for r in stab_rref],
        H.shape[1],
        found,
    )
    return mp.Pool(nprocs or os.cpu_count() or 1, _init_worker, args), found


def _coset_min_weight_brute(
    H: np.ndarray,
    stab: np.ndarray,
    max_weight: int | None = None,
    nprocs: int | None = None,
    label: str | None = None,
    even_only: bool = False,
) -> int:
    """Brute-force reference implementation of :func:`coset_min_weight`."""
    n = H.shape[1]
    max_weight = n if max_weight is None else max_weight
    pool, found = _brute_pool(H, stab, nprocs)
    try:
        for w in range(2 if even_only else 1, max_weight + 1, 2 if even_only else 1):
            if label is not None:
                print(f"  [{label}] checking weight {w}/{max_weight} ...", flush=True)
            found.value = 0
            tasks = [
                (prefix, w) for prefix in combinations(range(n), min(PREFIX_LEN, w))
            ]
            for hit in pool.imap_unordered(_search_prefix, tasks, chunksize=1):
                if hit:
                    found.value = 1
                    return w
    finally:
        pool.terminate()
        pool.join()
    return 0


def _enumerate_min_weight_logicals_brute(
    H: np.ndarray, stab: np.ndarray, weight: int, nprocs: int | None = None
) -> np.ndarray:
    """Brute-force reference implementation of
    :func:`enumerate_min_weight_logicals`."""
    n = H.shape[1]
    pool, _found = _brute_pool(H, stab, nprocs)
    try:
        tasks = [
            (prefix, weight)
            for prefix in combinations(range(n), min(PREFIX_LEN, weight))
        ]
        vints = [
            v
            for hits in pool.imap_unordered(_collect_prefix, tasks, chunksize=1)
            for v in hits
        ]
    finally:
        pool.terminate()
        pool.join()
    return _vints_to_matrix(vints, n)


# --------------------------------------------------------------------------- #
# Meet-in-the-middle min-weight search
#
# A weight-``w`` support ``S`` lies in ``ker(H)`` iff the XOR of its columns
# vanishes.  Split ``S = Q | T`` into a *query* part of size ``q`` and a
# *table* part of size ``h = w - q``; then ``syn(Q) == syn(T)``.  So instead
# of walking all ``C(n, w)`` supports we
#
#   1. tabulate the syndromes of every ``h``-subset once (sorted, shared with
#      the workers through fork), and
#   2. enumerate the ``C(n, q)`` query subsets in vectorised chunks and look
#      each syndrome up with a binary search.
#
# Every support is reached (any ``q``-subset of ``S`` is a valid query), and
# every hit is re-verified exactly.  For ``n = 256`` and ``w = 8`` this is
# ~2 * 1.7e8 subset syndromes instead of ~4e14 supports.
#
# Query subsets are grouped by their ``p`` smallest columns (a *prefix*); one
# task owns a contiguous block of prefixes, and the tails of a prefix come
# from a cached colex table in one shot.
# --------------------------------------------------------------------------- #
TABLE_MAX_ENTRIES = 300_000_000  # cap on C(n, h) for the tabulated side
QUERY_CHUNK = 4_000_000  # max query rows materialised per prefix
TASKS_PER_PROC = 16  # prefix blocks handed out per worker process

_COLEX: dict[tuple[int, int], np.ndarray] = {}
_M: dict = {}  # MITM worker globals (set in the parent before the fork)


def _colex_combos(n: int, r: int) -> np.ndarray:
    """All ``r``-subsets of ``range(n)`` as an ``(C(n, r), r)`` int16 array in
    colex order.  Colex sorts by the largest element first, so the leading
    ``C(m, r)`` rows are exactly the ``r``-subsets of ``range(m)`` for any
    ``m <= n``: one table serves every suffix range ``range(a, n)`` as
    ``a + table[:C(n - a, r)]``."""
    if (n, r) not in _COLEX:
        if r == 0:
            out = np.zeros((1, 0), dtype=np.int16)
        elif r == 1:
            out = np.arange(n, dtype=np.int16).reshape(-1, 1)
        else:
            prev = _colex_combos(n, r - 1)
            out = np.empty((math.comb(n, r), r), dtype=np.int16)
            off = 0
            for j in range(r - 1, n):  # subsets whose largest element is j
                cnt = math.comb(j, r - 1)
                out[off : off + cnt, : r - 1] = prev[:cnt]
                out[off : off + cnt, r - 1] = j
                off += cnt
        _COLEX[(n, r)] = out
    return _COLEX[(n, r)]


_KEY_ROT = (0, 17, 34, 51, 5, 22, 39, 56)


def _key_cols(H: np.ndarray) -> tuple[np.ndarray, bool]:
    """Columns of ``H`` as XOR-linear uint64 keys, plus an ``exact`` flag.

    With <= 64 checks the key *is* the syndrome; otherwise it is a rotate-XOR
    fold of the 64-bit words, so equal keys are necessary but not sufficient
    and hits must be re-verified against the exact column ints."""
    m, n = H.shape
    if m == 0:
        return np.zeros(n, dtype=np.uint64), True
    pb = np.packbits(H.T.astype(np.uint8), axis=1, bitorder="little")  # (n, ceil(m/8))
    nwords = (pb.shape[1] + 7) // 8
    buf = np.zeros((n, nwords * 8), dtype=np.uint8)
    buf[:, : pb.shape[1]] = pb
    words = buf.view("<u8")  # (n, nwords)
    key = words[:, 0].copy()
    for t in range(1, nwords):
        rot = _KEY_ROT[t % len(_KEY_ROT)]
        wt = words[:, t]
        key ^= (wt << np.uint64(rot)) | (wt >> np.uint64(64 - rot))
    return key, m <= 64


def _table_syn(keys: np.ndarray, idx: np.ndarray) -> np.ndarray:
    """XOR of ``keys`` over each row of the ``(N, r)`` index table ``idx``."""
    if idx.shape[1] == 0:
        return np.zeros(idx.shape[0], dtype=np.uint64)
    s = keys[idx[:, 0]]  # a fresh array; starting from it saves one pass
    for t in range(1, idx.shape[1]):
        s ^= keys[idx[:, t]]
    return s


def _mitm_split(n: int, w: int) -> tuple[int, int]:
    """``(h, q)``: table / query subset sizes for weight ``w``."""
    h = w // 2
    while h > 1 and math.comb(n, h) > TABLE_MAX_ENTRIES:
        h -= 1
    return h, w - h


def _query_prefix_len(n: int, q: int) -> int:
    """Smallest prefix length whose worst-case tail count fits ``QUERY_CHUNK``."""
    for p in range(1, q):
        if math.comb(n - p, q - p) <= QUERY_CHUNK:
            return p
    return max(q - 1, 0)


def _verify_vint(vint: int) -> bool:
    """Exact test: ``vint`` in ``ker(H)`` and not a stabilizer."""
    if not _M["exact"]:
        syn, v = 0, vint
        while v:
            low = v & -v  # lowest set bit
            syn ^= _M["cols"][low.bit_length() - 1]
            v ^= low
        if syn:
            return False
    return not _is_stabilizer(vint)


def _mitm_task(task: tuple[int, int, bool]) -> list[int]:
    """Scan the query prefixes ``P[lo:hi]``; return matching supports as
    bitmasks.  ``collect=False`` stops at the first verified hit (and honours
    the shared stop flag); ``collect=True`` returns every hit of the block."""
    lo, hi, collect = task
    keys, skeys, order, tidx = _M["keys"], _M["skeys"], _M["order"], _M["tidx"]
    P, tails_all, n, p = _M["P"], _M["tails"], _M["n"], _M["p"]
    rem = _M["q"] - p
    out: list[int] = []
    seen: set[int] = set()

    for prefix in P[lo:hi]:
        if not collect and _M["found"].value:
            break
        start = int(prefix[-1]) + 1 if p else 0
        tails = tails_all[: math.comb(n - start, rem)]  # relative to ``start``
        if len(tails) == 0:
            continue
        # key of prefix + tail, for every tail at once
        qk = np.bitwise_xor.reduce(keys[prefix]) ^ _table_syn(keys[start:], tails)
        # table rows with the same key: rows first[i] .. last[i]-1 for query hit[i]
        first = np.minimum(np.searchsorted(skeys, qk), len(skeys) - 1)
        hit = np.flatnonzero(skeys[first] == qk)
        if len(hit) == 0:
            continue
        first = first[hit]
        runs = np.searchsorted(skeys, qk[hit], side="right") - first
        # one row per (query, table row) pair
        qrow = np.repeat(hit, runs)
        trow = np.repeat(first - (np.cumsum(runs) - runs), runs) + np.arange(runs.sum())
        tsub = tidx[order[trow]]  # (pairs, h)
        qsub = np.concatenate(
            [np.broadcast_to(prefix, (len(qrow), p)), tails[qrow] + np.int16(start)],
            axis=1,
        )  # (pairs, q)
        disjoint = np.flatnonzero(
            ~(qsub[:, :, None] == tsub[:, None, :]).any(axis=(1, 2))
        )
        for support in np.concatenate(
            [qsub[disjoint], tsub[disjoint]], axis=1
        ).tolist():
            vint = sum(1 << j for j in support)
            if vint in seen:
                continue
            seen.add(vint)
            if _verify_vint(vint):
                out.append(vint)
                if not collect:
                    return out
    return out


def _mitm_weight(
    H: np.ndarray,
    stab: np.ndarray,
    w: int,
    collect: bool,
    nprocs: int,
    label: str | None,
    keys_exact: tuple[np.ndarray, bool] | None = None,
) -> list[int]:
    """Meet-in-the-middle over all weight-``w`` supports.

    Returns bitmasks of non-stabilizer kernel vectors of weight ``w``: all of
    them when ``collect`` is set, otherwise at most one (empty if none)."""
    n = H.shape[1]
    keys, exact = keys_exact if keys_exact is not None else _key_cols(H)
    h, q = _mitm_split(n, w)
    p = _query_prefix_len(n, q)

    t0 = time.perf_counter()
    tidx = _colex_combos(n, h)
    syn = _table_syn(keys, tidx)
    order = np.argsort(syn)
    skeys = syn[order]
    del syn
    if len(order) < 2**31:
        order = order.astype(np.int32)
    P = _colex_combos(n, p)
    stab_rref, stab_piv = rref_gf2(stab)
    found = mp.Value("b", 0)
    cols = _columns_as_int(H)

    _M.clear()
    _M.update(
        keys=keys, exact=exact, cols=cols, skeys=skeys, order=order, tidx=tidx,
        P=P, tails=_colex_combos(n, q - p), n=n, q=q, p=p, found=found,
    )  # fmt: skip
    _init_worker(cols, stab_piv, [_row_as_int(r) for r in stab_rref], n, found)

    ntask = max(1, min(len(P), nprocs * TASKS_PER_PROC))
    bounds = np.linspace(0, len(P), ntask + 1).astype(int)
    tasks = [
        (int(a), int(b), collect) for a, b in zip(bounds[:-1], bounds[1:]) if b > a
    ]
    if label is not None:
        print(
            f"  [{label}] weight {w}: table h={h} ({len(skeys):.3g} entries, "
            f"{time.perf_counter() - t0:.1f} s), query q={q} "
            f"({math.comb(n, q):.3g} subsets, {len(tasks)} tasks) ...",
            flush=True,
        )

    hits: list[int] = []
    pool = mp.get_context("fork").Pool(processes=min(nprocs, len(tasks)))
    try:
        for done, got in enumerate(
            pool.imap_unordered(_mitm_task, tasks, chunksize=1), 1
        ):
            hits.extend(got)
            if label is not None and (
                done == len(tasks) or done % max(1, len(tasks) // 4) == 0
            ):
                print(
                    f"  [{label}] weight {w}: {done}/{len(tasks)} tasks, "
                    f"{len(set(hits))} hits, {time.perf_counter() - t0:.1f} s",
                    flush=True,
                )
            if got and not collect:
                found.value = 1
                break
    finally:
        pool.terminate()
        pool.join()
        _M.clear()
    return sorted(set(hits))


def coset_min_weight(
    H: np.ndarray,
    stab: np.ndarray,
    max_weight: int | None = None,
    nprocs: int | None = None,
    label: str | None = None,
    even_only: bool = False,
    upper_bound: int | None = None,
) -> int:
    """Minimum Hamming weight of ``v`` with ``H @ v == 0`` (mod 2) that is
    NOT in ``rowspace(stab)`` -- i.e. the min-weight logical operator.

    Weights are searched in increasing order (meet-in-the-middle per weight),
    so the first weight with a hit is the minimum.

    ``upper_bound`` is the weight of a logical operator already in hand:
    weights ``>= upper_bound`` are never searched and ``upper_bound`` is
    returned when nothing lighter exists.  ``max_weight`` is the give-up cap
    (returns 0 when exceeded).  ``even_only`` skips odd weights (valid when
    ``all_kernel_weights_even(H)``).
    """
    if max_weight is None:
        max_weight = H.shape[1]
    if upper_bound is not None:
        max_weight = min(max_weight, upper_bound - 1)
    nprocs = nprocs or os.cpu_count() or 1
    keys_exact = _key_cols(H)

    for w in range(2 if even_only else 1, max_weight + 1, 2 if even_only else 1):
        if _mitm_weight(H, stab, w, False, nprocs, label, keys_exact):
            if label is not None:
                print(f"  [{label}] found logical at weight {w}", flush=True)
            return w
    if upper_bound is None:
        return 0
    if label is not None:
        print(
            f"  [{label}] nothing below the known weight-{upper_bound} logical",
            flush=True,
        )
    return upper_bound


def enumerate_min_weight_logicals(
    H: np.ndarray,
    stab: np.ndarray,
    weight: int,
    nprocs: int | None = None,
    label: str | None = None,
) -> np.ndarray:
    """All non-stabilizer kernel vectors of exactly ``weight`` (as rows): the
    shortest undetectable logical errors when ``weight`` is the distance."""
    n = H.shape[1]
    if weight <= 0:
        return np.zeros((0, n), np.int8)
    vints = _mitm_weight(H, stab, weight, True, nprocs or os.cpu_count() or 1, label)
    return _vints_to_matrix(vints, n)


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #
def main() -> None:
    fname = sys.argv[1] if len(sys.argv) > 1 else "test.txt"
    here = os.path.dirname(os.path.abspath(__file__))
    path = fname if os.path.isabs(fname) else os.path.join(here, fname)

    Hz, Hx = load_check_matrices(path)
    n = Hz.shape[1]
    k = n - rank_gf2(Hx) - rank_gf2(Hz)
    css_ok = not ((Hx.astype(np.int64) @ Hz.astype(np.int64).T) % 2).any()

    # Known logicals give an upper bound on each distance search.
    logical_Z = logical_operators(null_space_gf2(Hx), Hz)  # ker(Hx) \ rowspace(Hz)
    logical_X = logical_operators(null_space_gf2(Hz), Hx)  # ker(Hz) \ rowspace(Hx)
    X_pair, Z_pair = pair_logical_operators(logical_X, logical_Z)

    dist = {}
    for kind, H, stab, known in (
        ("Z", Hx, Hz, np.concatenate([logical_Z, Z_pair])),
        ("X", Hz, Hx, np.concatenate([logical_X, X_pair])),
    ):
        bound = int(known.sum(axis=1).min()) if k else None
        dist[kind] = coset_min_weight(
            H, stab, even_only=all_kernel_weights_even(H), upper_bound=bound
        )
    dz, dx = dist["Z"], dist["X"]

    print(f"[[n, k, d]] = [[{n}, {k}, {min(dx, dz)}]]  (dx = {dx}, dz = {dz})")
    print(f"CSS condition Hx*Hz^T == 0 : {css_ok}")


if __name__ == "__main__":
    main()
